framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        #failure_transport: failed

        transports:
            #amqp: '%env(MESSENGER_TRANSPORT_DSN)%'
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: false
                    #use_notify: true
                    #check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            #failed: 'doctrine://default?queue_name=failed'

        routing:
            # Route your messages to the transports
            # App\Message\RevueManagement\NumeroMessage: amqp
            #App\Message\RevueManagement\PdfToImageMessage: async
            #App\Message\RevueManagement\PdfToImageUpdateMessage: async