snc_redis:
  clients:
    default:
      type: predis
      alias: default
      dsn: '%env(resolve:REDIS_URL)%'
      logging: '%kernel.debug%'
    doctrine:
      type: predis
      alias: doctrine
      dsn: "%env(REDIS_URL)%"
      logging: '%kernel.debug%'