twig:
    form_themes: ['bootstrap_4_layout.html.twig']  
    default_path: '%kernel.project_dir%/templates'
    globals: 
        site_help: '%env(SITE_HELP)%'
        
services:
    Twig\Extension\StringLoaderExtension:
        tags: ['twig.extension']