# monolog:
#     handlers:
#         main:
#             type: stream
#             path: "%kernel.logs_dir%/%kernel.environment%.log"
#             level: debug
#             channels: ["!event"]
#         # uncomment to get logging in your browser
#         # you may have to allow bigger header sizes in your Web server configuration
#         #firephp:
#         #    type: firephp
#         #    level: info
#         #chromephp:
#         #    type: chromephp
#         #    level: info
#         console:
#             type: console
#             process_psr_3_messages: false
#             channels: ["!event", "!doctrine", "!console"]
monolog:
    channels: ["supervisor"]   # Custom channel
    handlers:
        main:
            type: rotating_file #stream            
            path: "%kernel.logs_dir%/%kernel.environment%.all.log"
            level: debug
            max_files: 20
            channels: ["!event"]
        login:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.auth.log"
            level:          info
            channels:       ["security"]
        supervisor:
            type:           stream
            path:           "%kernel.logs_dir%/%kernel.environment%.supervisor.log"
            level:          info
            channels:       ["supervisor"]            
        main_error:
            type:           fingers_crossed
            action_level:   error
            handler:        streamed_error
        streamed_error:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.error.log"
            level:          error
        main_critical:
            type:           fingers_crossed
            action_level:   critical
            handler:        grouped_critical
        grouped_critical:
            type:           group
            members:        [streamed_critical, buffered_critical]
        streamed_critical:
            type:           rotating_file
            max_files:      15
            path:           "%kernel.logs_dir%/%kernel.environment%.critical.log"
            level:          critical
        buffered_critical:
            type:           buffer
            handler:        swift_critical
        swift_critical:
            type:           swift_mailer
            from_email:     test-veille@xxx.com
            to_email:       yi.shen@xxx.com
            subject:        Une erreur critique est survenue ! (server veille)
            level:          critical
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]            